//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the tool.
//     Runtime version: 4.0.30319.18444
//
//     Changes to this file, It may cause illegal operation under the following situations,
//     Loss when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleROHookCS.Properties
{
    using System;

    /// <summary>
    ///   A strongly typed resource class for searching localized strings and more.
    /// </summary>
    // This class has a StronglyTypedResourceBuilder class of ResGen
    // Or it was automatically generated using a tool like Visual Studio.
    // To add or remove members, edit the .ResX file with the /str option
    // Rerun ResGen or rebuild the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
            // Empty
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleROHookCS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   For all search resources, use this strongly typed resource class,
        ///   Override the CurrentUICulture property of the current thread.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }
    }
}
